project:
  type: website
  output-dir: docs

website:
  title: "Portfolio of Uday"
  navbar:
    left:
    - about me.qmd
    - work experience.qmd
    - projects.qmd  
    
format:
  html:
    theme: Superhero